name: InvPeek
version: '1.0-SNAPSHOT'
main: invpeek.inv_peek.Inv_peek
api-version: 1.19
authors: [ Siliwolf ]
commands:
  invpeek:
    description: See and modify a player's inventory
    usage: /invsee <PLAYER_NAME>